Ability to override how psake's internal logging is handled
psake/psake pull request #301
Opened 2020-06-20 16:28 UTC by UberDoodles

## Description

There is a new WriteOutput function, which is used throughout the psake code whenever messages need to be logged. The function simply passes the message and message type to an "outputHandler" script block, which can be overridden in psake-config. So you can override exactly how output is handled by overriding that outputHandler script block.

The default outputHandler script block further routes the output according to it's output type (warning, verbose, error, etc) to corresponding script blocks which can also be overridden by psake-config. So you also have the option of overriding how a single type of output is handled.

The default outputHandlers for each message type outputs the message exactly as it would have been prior to this new feature, so it is a non-breaking change.

## Related Issue

#65 

## Motivation and Context

As described in the issue, if your psake build file uses a different method of logging to psake's internal logging method, it can be difficult to try and handle the messages from each consistently. This change allows you to make psake's internal logging more consistent with your own. You can even have psake's messages routed to your own custom functions.

## How Has This Been Tested?

New spec files added to verify the basic functionality, that all of psake's internal logging uses the new WriteOutput function, and that it handles situations where the config items have been overridden with invalid values.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-29 10:16 UTC, jozefchmelar commented
This is very useful! I use it in my own fork of psake. I was about to make a PR but it turns out you made it first! Good work.

2024-10-12 04:46 UTC, HeyItsGilbert requested changes
I would say I like 99% of this. Should we assert that the default handlers are available?

Do we need/want a verbose output?

2024-10-12 04:46 UTC, HeyItsGilbert commented on src/private/WriteOutput.ps1
> +        [string]$OutputType = "default"
I don't love that this is a string. This really should be an enum or validated set.

2024-10-12 04:46 UTC, HeyItsGilbert commented on src/private/WriteTaskTimeSummary.ps1
> +        WriteOutput ("-" * 70)
Probably from the rebase, but I think we should keep the taskNameFormat calls.

2024-10-12 04:46 UTC, HeyItsGilbert commented on psakeFile.ps1
> +Task default -depends Test-Task
This an extra file?

2025-03-01 05:33 UTC, HeyItsGilbert commented on src/private/WriteOutput.ps1
> +        [string]$OutputType = "default"
Changing this to enum broke things. We can revisit later.

2025-03-01 05:43 UTC, merged